[package]
name = "discord_dm_analyser"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
itertools = "0.13.0"
fxhash = "0.2.1"
num-format = "0.4.4"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde-this-or-that = "0.4.2"
anyhow = "1.0.93"
